<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="SuiteKanya" duration-ms="84124" started-at="2022-10-25T11:11:54Z" finished-at="2022-10-25T11:13:18Z">
    <groups>
    </groups>
    <test name="TestKanya2" duration-ms="38524" started-at="2022-10-25T11:11:54Z" finished-at="2022-10-25T11:12:32Z">
      <class name="sample.ErrorValidations">
        <test-method status="PASS" signature="launchApplication()[pri:0, instance:sample.ErrorValidations@1e730495]" name="launchApplication" is-config="true" duration-ms="7866" started-at="2022-10-25T16:41:54Z" finished-at="2022-10-25T16:42:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method status="PASS" signature="errorHandling()[pri:0, instance:sample.ErrorValidations@1e730495]" name="errorHandling" duration-ms="924" started-at="2022-10-25T16:42:01Z" finished-at="2022-10-25T16:42:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- errorHandling -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:sample.ErrorValidations@1e730495]" name="tearDown" is-config="true" duration-ms="155" started-at="2022-10-25T16:42:02Z" finished-at="2022-10-25T16:42:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="launchApplication()[pri:0, instance:sample.ErrorValidations@1e730495]" name="launchApplication" is-config="true" duration-ms="3105" started-at="2022-10-25T16:42:03Z" finished-at="2022-10-25T16:42:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method status="PASS" signature="prodcutErrorHandling()[pri:0, instance:sample.ErrorValidations@1e730495]" name="prodcutErrorHandling" duration-ms="10232" started-at="2022-10-25T16:42:06Z" finished-at="2022-10-25T16:42:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- prodcutErrorHandling -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:sample.ErrorValidations@1e730495]" name="tearDown" is-config="true" duration-ms="16224" started-at="2022-10-25T16:42:16Z" finished-at="2022-10-25T16:42:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- sample.ErrorValidations -->
    </test> <!-- TestKanya2 -->
    <test name="TestKanya1" duration-ms="84124" started-at="2022-10-25T11:11:54Z" finished-at="2022-10-25T11:13:18Z">
      <class name="sample.StandaloneProjectDuplicate">
        <test-method status="PASS" signature="launchApplication()[pri:0, instance:sample.StandaloneProjectDuplicate@11dc3715]" name="launchApplication" is-config="true" duration-ms="7874" started-at="2022-10-25T16:41:54Z" finished-at="2022-10-25T16:42:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method status="PASS" signature="step01()[pri:0, instance:sample.StandaloneProjectDuplicate@11dc3715]" name="step01" duration-ms="25590" started-at="2022-10-25T16:42:01Z" finished-at="2022-10-25T16:42:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- step01 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:sample.StandaloneProjectDuplicate@11dc3715]" name="tearDown" is-config="true" duration-ms="16197" started-at="2022-10-25T16:42:27Z" finished-at="2022-10-25T16:42:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="launchApplication()[pri:0, instance:sample.StandaloneProjectDuplicate@11dc3715]" name="launchApplication" is-config="true" duration-ms="4034" started-at="2022-10-25T16:42:43Z" finished-at="2022-10-25T16:42:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method status="FAIL" signature="step02()[pri:0, instance:sample.StandaloneProjectDuplicate@11dc3715]" name="step02" duration-ms="5305" started-at="2022-10-25T16:42:47Z" finished-at="2022-10-25T16:42:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at org.testng.Assert.assertEquals(Assert.java:296)
	at sample.StandaloneProjectDuplicate.step02(StandaloneProjectDuplicate.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- step02 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:sample.StandaloneProjectDuplicate@11dc3715]" name="tearDown" is-config="true" duration-ms="16221" started-at="2022-10-25T16:42:53Z" finished-at="2022-10-25T16:43:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="launchApplication()[pri:0, instance:sample.StandaloneProjectDuplicate@11dc3715]" name="launchApplication" is-config="true" duration-ms="3122" started-at="2022-10-25T16:43:09Z" finished-at="2022-10-25T16:43:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method status="FAIL" signature="step02()[pri:0, instance:sample.StandaloneProjectDuplicate@11dc3715]" name="step02" duration-ms="5294" started-at="2022-10-25T16:43:12Z" finished-at="2022-10-25T16:43:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at org.testng.Assert.assertEquals(Assert.java:296)
	at sample.StandaloneProjectDuplicate.step02(StandaloneProjectDuplicate.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1049)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- step02 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:sample.StandaloneProjectDuplicate@11dc3715]" name="tearDown" is-config="true" duration-ms="111" started-at="2022-10-25T16:43:18Z" finished-at="2022-10-25T16:43:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- sample.StandaloneProjectDuplicate -->
    </test> <!-- TestKanya1 -->
  </suite> <!-- SuiteKanya -->
</testng-results>
